version: '3.0'
services:
  web:
    image: alexcheng/magento2
    ports:
      - "8001:80"
    volumes:
      - magento-data:/var/www/html
    env_file:
      - env
volumes:
  magento-data:
  db-data: